name: sparse_edit
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - scikit-learn
  - scikit-image
  - numpy
  - scipy
  - py-opencv
  - pillow
  - cvxopt
  - pip
  - git
  - cython
  - pip:
     - qtwidgets
     - git+https://github.com/yig/python-qtwidgets#egg=qtwidgets
     - qtpy
     - pyside6
     - torch==1.10.1
     - torchvision==0.11.2
     - torchaudio==0.10.1
prefix: /Users/tedchao/opt/miniconda3/envs/sparsity
